version: "3"

services:
  postgres:
    image: postgres:9.5
    volumes:
      - cachet_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    restart: always
  cachet:
    image: cachethq/docker
    ports:
      - 8200:8000
    links:
      - postgres:postgres
    environment:
      - APP_URL=${APP_URL}
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_PREFIX=chq_
      - APP_KEY=${APP_KEY:-null}
      - APP_LOG=errorlog
      - DEBUG=false
    depends_on:
      - postgres
    restart: on-failure

volumes:
  cachet_storage:
    external: true
